### ISSUE TITLE
Header files

### ISSUE THREAD

**Issue by int0x80-sys** [jlsuh/relay-chat#13]
Buenas. Paso para dar un par de feedbacks.

Te quedó genial el proyecto 👏 . Solo hay dos cuestiones. Una técnica y otra un toque mas de estilo.

1) En los header files tratá de no declarar variables globales, y menos variable statics. Generalmente como una regla a seguir es que en los header files este la interfaz pública con la que interactuan otros módulos con el módulo en cuestion. Pongo como ejemplo a la interfaz del server. En tu .h solo tendría que figurar las funciones con la que te comunicas con el server:

```C
#ifndef SRC_SERVER_H_
#define SRC_SERVER_H_

#include "common_utils.h"

#define SERVER_CONFIG "cfg/server.config"
#define SERVER_IP "IP"
#define SERVER_PORT "PORT"

void handle_connections(int);
void* suscription_handler(void*);
void handle_chat_room(t_user*);
void lead_chat_room(t_user*);
void send_msg_to_all_users(t_user*, char*);
int get_user_index(t_user*);
t_user* recv_user_info(int);
t_chat_room* find_room(uint32_t);
void sig_int_handler(int);
int init_server(char*, char*);

#endif
```
Las variables statics, si las necesitas para uso interno, declaralas dentro del .c. Si lo declarás dentro del .h, cada archivo .c que incluya el header va a estar creando sus propias variables (al ser static, esas variables globales quedan únicas por cada archivo .c).

2) Colocale los nombres a los argumentos en las declaraciones de las funciones. Es como el tema de escoger un nombre para las funciones. Un buen nombre a los argumentos te da una idea de que es lo representa. Ademas, generalmente uno cuando va a mirar como interactuar con determinada interfaz (por ejemplo, con el server) mira el .h.

Saludos y suerte con el tp :wave:

**Comment by jlsuh** [comment]
@int0x80-sys
Qué buenos feedbacks son los suyos. Los tendré presente para el tp :D !
