### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by int0x80-sys** [jlsuh/relay-chat#2]
Hola. Re chusma pero:

![imagen](https://user-images.githubusercontent.com/73644770/130532368-7bfcd8e9-483c-4c0a-a041-1a9f536caee3.png)

Eso es porque despues de un label en un switch no podes declarar una variable (aunque creo que ia tu sabes)

![imagen](https://user-images.githubusercontent.com/73644770/130532456-dd28059d-06e3-4041-aa0c-a2bb0403f4a0.png)

Espero con ansias el release (?

Saludos 👋

**Comment by jlsuh** [comment]
@int0x80-sys 
Te juro que iba a pasar por uteñatos a dejar la consulta, pero al final no lo hice.
Te agradezco la observación, lo estaré corrigiendo 🤝
